---
- name: DotFiles Config
  hosts: localhost
  vars:
    ansible_remote_tmp: ${XDG_CACHE_HOME-${HOME}/.cache}/ansible-tmp/
  connection: local

  tasks:
    - name: Create bin folder if missing
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local/bin"
        state: directory
        mode: "0755"
      tags:
        - always

    - name: Add bin folder to $PATH
      become: true
      ansible.builtin.copy:
        src: "{{ ansible_user_dir }}/.config/dotfiles/bin/set_path.sh"
        dest: /etc/profile.d/set_path.sh
        owner: root
        group: root
        mode: "0644"
      tags:
        - always

    - name: Link dotfiles script to bin folder
      ansible.builtin.file:
        src: "{{ ansible_user_dir }}/.config/dotfiles/bin/dotfiles"
        dest: "{{ ansible_user_dir }}/.local/bin/dotfiles"
        state: link
      tags:
        - always

    - name: Update package cache
      become: true
      community.general.pacman:
        update_cache: true
      tags:
        - always

    - name: Set roles
      ansible.builtin.set_fact:
        roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles }}"
      tags:
        - always

# vim:ft=yaml.ansible
