---
- name: Install greetd and nwg-hello
  become: true
  community.general.pacman:
    # update_cache: true
    name:
      - greetd
      - nwg-hello
      - cage
    state: present

- name: Copy greetd config file
  become: true
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/greetd/config.toml
    owner: root
    group: root
    mode: "0644"

- name: Copy nwg-hello config file
  become: true
  ansible.builtin.copy:
    src: nwg-hello/
    dest: /etc/nwg-hello/
    owner: root
    group: root
    mode: "0644"

- name: Create backgrounds folder
  become: true
  ansible.builtin.file:
    path: /usr/local/share/backgrounds
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download Gruvbox wallpaper
  become: true
  ansible.builtin.get_url:
    url: https://gruvbox-wallpapers.pages.dev/wallpapers/minimalistic/gruv-abstract-maze.png
    dest: /usr/local/share/backgrounds/gruvbox-wallpaper.png
    owner: root
    group: root
    mode: "0644"

- name: Enable greetd service
  become: true
  ansible.builtin.systemd_service:
    name: greetd
    enabled: true
