---
- name: Install flatpak package manager
  become: true
  community.general.pacman:
    # update_cache: true
    name:
      - flatpak
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-hyprland
    state: present

- name: Install steam-devices packages from AUR
  kewlfft.aur.aur:
    use: "{{ ansible_aur_helper }}"
    name: steam-devices-git
    state: present

- name: Modify flathub remote
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://mirror.sjtu.edu.cn/flathub/flathub.flatpakrepo
    state: present
    method: user

- name: Get stats of the overrides path
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.local/share/flatpak/overrides"
  register: overrides

- name: Delete overrides folder if it is not a link
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/flatpak/overrides"
    state: absent
  when: overrides.stat.islnk is defined and overrides.stat.islnk == False

- name: Apply overrides
  ansible.builtin.file:
    src: "{{ role_path }}/files/overrides"
    dest: "{{ ansible_user_dir }}/.local/share/flatpak/overrides"
    state: link

- name: Install packages using flatpak
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    state: present
    method: user

- name: Create brave data folder if missing
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.var/app/com.brave.Browser/config"
    state: directory
    mode: "0755"

- name: Link Chrome flags for brave browser
  ansible.builtin.copy:
    src: "chrome-flags.conf"
    dest: "{{ ansible_user_dir }}/.var/app/com.brave.Browser/config/brave-flags.conf"
    mode: "0644"

# - name: Create ungoogled chromium data folder if missing
#   ansible.builtin.file:
#     path: "{{ ansible_user_dir }}/.var/app/io.github.ungoogled_software.ungoogled_chromium/config"
#     state: directory
#     mode: "0755"
#
# - name: Link Chrome flags for ungoogled chromium
#   ansible.builtin.copy:
#     src: "chrome-flags.conf"
#     dest: "{{ ansible_user_dir }}/.var/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium-flags.conf"
#     mode: "0644"
