---
- name: Setting xdg env vars
  become: true
  ansible.builtin.copy:
    src: "xdg.sh"
    dest: "/etc/profile.d/xdg.sh"
    owner: root
    group: root
    mode: "0644"

- name: Link npmrc file
  ansible.builtin.file:
    src: "{{ role_path }}/files/npm"
    dest: "{{ ansible_user_dir }}/.config/npm"
    state: link
