# SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "catppuccin-mocha-light-cursors"

# Font name and size
font_name = "Monospace Bold 14"

# Icon theme name
icon_theme_name = "ePapirus-Dark"

# GTK theme name
theme_name = "Colloid-Teal-Dark-Gruvbox"

[commands]
# The command used to reboot the system
reboot = [ "systemctl", "reboot" ]

# The command used to shut down the system
poweroff = [ "systemctl", "poweroff" ]
