#!/usr/bin/env bash

export FZF_DEFAULT_OPTS=" \
 --color=bg:#282828,fg:#ebdbb2,hl:#d65d0e\
 --color=bg+:#504945,fg+:#ebdbb2,hl+:#fabd2f\
 --color=info:#83a598,border:#458588,prompt:#98971a\
 --color=pointer:#282828,marker:#fb4934,spinner:#fb4934,header:#cc241d"

case "$1" in
preview)
    row="$2"
    if echo "$row" | grep -vqP '^\d+\t\[\[ binary data .* \]\]'; then
        echo "$row" | cliphist decode | bat --color=always --style=plain --wrap=character --terminal-width=56 --theme=gruvbox-dark
    else
        echo "$row" | cliphist decode | chafa -f sixel -s "${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}"
    fi
    ;;

*)
    id="$(cliphist list | fzf --preview "$(realpath "$0") preview {}")"
    test -z "$id" && exit

    cliphist decode <<<"$id" | wl-copy
    ;;

esac
