#!/bin/sh

WALL=`find ~/wallpapers -name '*.png' -or -name '*.jpg' -or -name '*.jpeg' -or -name '*.webp' | shuf -n1`

export SWWW_TRANSITION=random
export SWWW_TRANSITION_FPS=60
export SWWW_TRANSITION_STEP=10
export SWWW_TRANSITION_DURATION=1

swww img ${WALL}

echo ${WALL} > ~/.cache/current_wall.txt
